### ISSUE TITLE
A question about Sec 3.2 in paper

### ISSUE THREAD

**Issue by szxSpark** [mswellhao/PacSum#4]
"where v_s and v_s' are two different representations of sentence s via two differently parameter-ized BERT encoders"

![image](https://user-images.githubusercontent.com/23302810/75786640-8eca6200-5da0-11ea-9090-5156a409142a.png)
In your code, i just find only one BERT encoder. Cay you teach me how to understand this sentcence? Thank you.

**Comment by zhanghaiting001** [comment]
@szxSpark  Have you gotten the meaning of the objective?  maximize or minimize?  Thank you

**Comment by mswellhao** [comment]
Instead of using one BERT model to encode s and just finetune the only BERT model throughout the training, we want to emphasize here that we use two separate BERT models (two copy of models without weight sharing) to encode s as v_s and v_s^prime, and fine-tuning two models during the training.

**Comment by WhyCube** [comment]
@mswellhao 想问一下如果是同时finetune 两个bert么，如果是的话，之后哪一个作为 你的微调后的模型呢?
我理解的是不是 两个bert但是只更新其中一个的参数？
